"""add Choice.new_field

Revision ID: 390e37c6275d
Revises: d3618fdc14ba
Create Date: 2024-03-05 21:21:07.989293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390e37c6275d'
down_revision = 'd3618fdc14ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('new_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'new_field')
    # ### end Alembic commands ###
