"""remove Choice.new_field

Revision ID: da220e6cdde0
Revises: 390e37c6275d
Create Date: 2024-03-05 21:24:33.088507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da220e6cdde0'
down_revision = '390e37c6275d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'new_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('new_field', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
